import type { GrammarStage } from '../store/types';

/**
 * The grammar "spine" that turns the phrasebook into a ramped course.
 *
 * Ordered by Serbian SPOKEN-frequency difficulty, not textbook case number.
 * Present tense + accusative is the early mountain; the dative "experiencer"
 * (feelings) and clitic word-order are the mid mountain; aspect is the summit.
 * Each phrase is assigned a stage in src/data/phrase-meta.json (generated by
 * scripts/tag-phrases.mjs) using `stageForFeatures` below.
 */
export const STAGES: GrammarStage[] = [
  {
    id: 0,
    key: 'chunks',
    title: 'Chunks & Set Phrases',
    blurb: 'Fixed expressions you use whole — greetings, reactions, "volim te".',
    features: ['chunk'],
  },
  {
    id: 1,
    key: 'present',
    title: 'Present Tense',
    blurb: 'Saying what you do — present-tense verbs, "hoću/mogu/moram da…".',
    features: ['present'],
  },
  {
    id: 2,
    key: 'accusative',
    title: 'Objects · Accusative',
    blurb: '"I want a coffee" — the accusative ending on the thing you act on.',
    features: ['accusative'],
  },
  {
    id: 3,
    key: 'genitive',
    title: 'Genitive',
    blurb: '"There isn\'t…", "from / at" — the workhorse genitive triggers.',
    features: ['genitive'],
  },
  {
    id: 4,
    key: 'past-future',
    title: 'Past & Future',
    blurb: 'Talking about then — past (agrees with gender) and future.',
    features: ['past', 'future'],
  },
  {
    id: 5,
    key: 'dative',
    title: 'Feelings · Dative',
    blurb: '"I like it", "I miss you" — the dative experiencer constructions.',
    features: ['dative'],
  },
  {
    id: 6,
    key: 'loc-ins',
    title: 'Place & "With"',
    blurb: '"in town", "with you" — locative and instrumental.',
    features: ['locative', 'instrumental'],
  },
  {
    id: 7,
    key: 'clitics',
    title: 'Word Order · Clitics',
    blurb: 'Sounding native — the 2nd-position clitic cluster ("si mi ga").',
    features: ['clitic-cluster'],
  },
  {
    id: 8,
    key: 'aspect',
    title: 'Aspect & Complex',
    blurb: 'Perfective vs imperfective, relative clauses, conditional.',
    features: ['aspect', 'complex'],
  },
];

export const STAGE_COUNT = STAGES.length;

export function getStage(id: number): GrammarStage | undefined {
  return STAGES.find((s) => s.id === id);
}

/**
 * Highest stage whose introducing features appear in the phrase. Keep this in
 * sync with the duplicate copy in scripts/tag-phrases.mjs (it can't import TS).
 */
export function stageForFeatures(features: string[]): number {
  if (features.includes('chunk')) return 0;
  for (let i = STAGES.length - 1; i >= 1; i--) {
    if (STAGES[i].features.some((f) => features.includes(f))) return STAGES[i].id;
  }
  return 1;
}
