import type { PhraseMeta } from '../store/types';
import metaRaw from './phrase-meta.json';

/**
 * Per-phrase difficulty + grammar-stage metadata, generated by
 * scripts/tag-phrases.mjs (heuristic, refinable by Claude/hand later).
 * Drives stage-aware sequencing of new content and the difficulty badges.
 */
const meta = metaRaw as Record<string, PhraseMeta>;

const DEFAULT: PhraseMeta = {
  stage: 1,
  difficulty: 3,
  isChunk: false,
  caseSet: [],
  tense: 'none',
  cliticCount: 0,
  idiomatic: false,
};

export function getPhraseMeta(id: string): PhraseMeta {
  return meta[id] ?? DEFAULT;
}

export function phraseStage(id: string): number {
  return meta[id]?.stage ?? DEFAULT.stage;
}

export function phraseDifficulty(id: string): number {
  return meta[id]?.difficulty ?? DEFAULT.difficulty;
}

export function isChunkPhrase(id: string): boolean {
  return meta[id]?.isChunk ?? false;
}

export { meta as phraseMetaMap };
